/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Facility {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'iconName' : string,
}
export interface NewsArticle {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'shortDescription' : string,
  'category' : string,
}
export interface PrincipalMessage {
  'title' : string,
  'name' : string,
  'imageUrl' : string,
  'message' : string,
}
export interface _SERVICE {
  'getFacilities' : ActorMethod<[], Array<Facility>>,
  'getNewsArticles' : ActorMethod<[], Array<NewsArticle>>,
  'getPrincipalMessage' : ActorMethod<[], PrincipalMessage>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];