/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Facility = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'shortDescription' : IDL.Text,
  'category' : IDL.Text,
});
export const PrincipalMessage = IDL.Record({
  'title' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
  'getNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getPrincipalMessage' : IDL.Func([], [PrincipalMessage], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Facility = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'shortDescription' : IDL.Text,
    'category' : IDL.Text,
  });
  const PrincipalMessage = IDL.Record({
    'title' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'getFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
    'getNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getPrincipalMessage' : IDL.Func([], [PrincipalMessage], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };